#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-gradle-versions-plugin
Version  : 0.21.0
Release  : 1
URL      : https://github.com/ben-manes/gradle-versions-plugin/archive/v0.21.0.tar.gz
Source0  : https://github.com/ben-manes/gradle-versions-plugin/archive/v0.21.0.tar.gz
Source1  : https://repo.gradle.org/gradle/libs-releases/com/github/ben-manes/gradle-versions-plugin/0.21.0/gradle-versions-plugin-0.21.0.jar
Source2  : https://repo.gradle.org/gradle/libs-releases/com/github/ben-manes/gradle-versions-plugin/0.21.0/gradle-versions-plugin-0.21.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-gradle-versions-plugin-data = %{version}-%{release}
Requires: mvn-gradle-versions-plugin-license = %{version}-%{release}
BuildRequires : buildreq-mvn
BuildRequires : gradle

%description
# Gradle Versions Plugin
In the spirit of the [Maven Versions Plugin](http://www.mojohaus.org/versions-maven-plugin),
this plugin provides a task to determine which dependencies have updates. Additionally, the plugin
checks for updates to Gradle itself.

%package data
Summary: data components for the mvn-gradle-versions-plugin package.
Group: Data

%description data
data components for the mvn-gradle-versions-plugin package.


%package license
Summary: license components for the mvn-gradle-versions-plugin package.
Group: Default

%description license
license components for the mvn-gradle-versions-plugin package.


%prep
%setup -q -n gradle-versions-plugin-0.21.0

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-gradle-versions-plugin
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-gradle-versions-plugin/LICENSE.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/ben-manes/gradle-versions-plugin/0.21.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/github/ben-manes/gradle-versions-plugin/0.21.0/gradle-versions-plugin-0.21.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/ben-manes/gradle-versions-plugin/0.21.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/github/ben-manes/gradle-versions-plugin/0.21.0/gradle-versions-plugin-0.21.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/github/ben-manes/gradle-versions-plugin/0.21.0/gradle-versions-plugin-0.21.0.jar
/usr/share/java/.m2/repository/com/github/ben-manes/gradle-versions-plugin/0.21.0/gradle-versions-plugin-0.21.0.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-gradle-versions-plugin/LICENSE.txt
